import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex justify-center items-center h-screen w-screen' >
        <h1 className="text-3xl font-bold underline text-primary ">
          Hello world!
        </h1>
        <div className='bg-gradient-pink-to-blue from-secondaryBlue  to-secondaryPurple space-y-5 h-60 w-60 border-2'></div>
        <div className='bg-gradient-pink-to-baby-blue space-y-5 h-60 w-60 border-2'></div>
        <div className='bg-gradient-purple-to-pink space-y-5 h-60 w-60 border-2'></div>
      </main>
    </>
  )
}
